Document: seabreeze
Title: Debian seabreeze Manual
Author: <insert document author here>
Abstract: This manual describes what seabreeze is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/seabreeze/seabreeze.sgml.gz

Format: postscript
Files: /usr/share/doc/seabreeze/seabreeze.ps.gz

Format: text
Files: /usr/share/doc/seabreeze/seabreeze.text.gz

Format: HTML
Index: /usr/share/doc/seabreeze/html/index.html
Files: /usr/share/doc/seabreeze/html/*.html
